# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61c4eb4ee0516b104524403fbe890ae6"
name = "All in one countdown timers"
handle = "all-in-one-countdown-timers"
application_url = "https://boating-graph-covers-tunes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appdeveloplearn.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://boating-graph-covers-tunes.trycloudflare.com/auth/callback",
  "https://boating-graph-covers-tunes.trycloudflare.com/auth/shopify/callback",
  "https://boating-graph-covers-tunes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
