# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab0df3f50c77119e526f6299a60c2ba2"
name = "flash-sale-coundown"
handle = "flash-sale-coundown"
application_url = "https://carpet-decisions-christ-patrol.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appdeveloplearn.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://carpet-decisions-christ-patrol.trycloudflare.com/auth/callback",
  "https://carpet-decisions-christ-patrol.trycloudflare.com/auth/shopify/callback",
  "https://carpet-decisions-christ-patrol.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
